import Head from "next/head";
import Image from "next/image";
import toggle from "../public/toggle.png";
import facebook from "../public/facebook.png";
import twitter from "../public/twitter.png";
import instagram from "../public/instagram.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Thailand | Landing Page UI Design</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <a href="#" className="logo">
          Travel
        </a>
        <div className="toggle">
          <Image className="img" alt="Toggle" src={toggle} />
        </div>
      </header>

      <div className="banner">
        <video src="/video.mp4" muted autoPlay loop type="mp4"></video>

        <div className="textBox">
          <h2>Wonderful Tailand</h2>
          <p>
            Lorem Ipsum is simply dummy text of the printing and typesetting
            industry. Lorem Ipsum has been the industry's standard dummy text
            ever since the 1500s, when an unknown printer took a galley of type
            and scrambled it to make a type specimen book. It has survived not
            only five centuries, but also the leap into electronic typesetting,
            remaining essentially unchanged. It was popularised in the 1960s
            with the release of Letraset sheets containing Lorem Ipsum passages,
            and more recently with desktop publishing software like Aldus
            PageMaker including versions of Lorem Ipsum.
          </p>
          <a href="#">Read More</a>
        </div>

        <div className="videoBx">
          <video src="/video.mp4" muted autoPlay loop type="mp4"></video>
        </div>

        <ul className="sci">
          <li>
            <a href="#">
              <Image className="img" alt="Facebook" src={facebook} />
            </a>
          </li>
          <li>
            <a href="#">
              <Image className="img" alt="Twitter" src={twitter} />
            </a>
          </li>
          <li>
            <a href="#">
              <Image className="img" alt="Instagram" src={instagram} />
            </a>
          </li>
        </ul>
      </div>
    </div>
  );
}
